# Generated by Django 3.1.7 on 2021-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Instructor_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
